name: widgetbook_workspace
description: Dedicated Widgetbook workspace for the POC Flutter app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.22.0
  poc_widgetbook_app:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true